import styles from "./AgentPanel.module.css";
import type { Agent, AgentMessage } from "@/lib/supabase/types";

interface Props {
  agent: Agent;
  messages: AgentMessage[];
}

function timeAgo(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1) return "JUST NOW";
  if (m < 60) return `${m}M AGO`;
  const h = Math.floor(m / 60);
  return `${h}H AGO`;
}

const MSG_ICONS: Record<string, string> = {
  log: "▸",
  alert: "⚠",
  report: "◈",
  commentary: "◇",
};

const MSG_COLORS: Record<string, string> = {
  log: "dim",
  alert: "amber",
  report: "furnace",
  commentary: "blue",
};

export default function AgentPanel({ agent, messages }: Props) {
  return (
    <div className={styles.panel}>
      <div className={styles.header}>
        <div className={styles.agentIdent}>
          <div className={styles.agentIconWrap}>
            <span className={styles.agentIcon}>⬡</span>
          </div>
          <div className={styles.agentInfo}>
            <span className={styles.agentName}>{agent.name}</span>
            <span className={styles.agentDesig}>{agent.designation}</span>
          </div>
        </div>
        <div className={styles.agentMetrics}>
          <div className={styles.metric}>
            <span className={styles.metricLabel}>ENERGY</span>
            <span className={`${styles.metricValue} ${agent.energy_level < 30 ? styles.metricWarn : ""}`}>
              {agent.energy_level}%
            </span>
          </div>
          <div className={styles.metric}>
            <span className={styles.metricLabel}>INTEGRITY</span>
            <span className={`${styles.metricValue} ${agent.integrity < 50 ? styles.metricCrit : ""}`}>
              {agent.integrity}%
            </span>
          </div>
        </div>
      </div>

      {/* Status row */}
      <div className={styles.statusRow}>
        <div className={styles.statusItem}>
          <span className={styles.statusLabel}>STATE</span>
          <span className={`${styles.statusValue} ${styles[`state_${agent.state}`]}`}>
            {agent.state.toUpperCase()}
          </span>
        </div>
        <div className={styles.statusDivider} />
        <div className={styles.statusItem}>
          <span className={styles.statusLabel}>MODE</span>
          <span className={`${styles.statusValue} ${agent.mode === "autonomous" ? styles.stateGreen : styles.stateAmber}`}>
            {agent.mode.toUpperCase()}
          </span>
        </div>
      </div>

      {/* Last action */}
      {agent.last_action && (
        <div className={styles.lastAction}>
          <span className={styles.lastActionLabel}>LAST OPERATOR LOG</span>
          <p className={styles.lastActionText}>{agent.last_action}</p>
          {agent.last_action_at && (
            <span className={styles.lastActionTime}>{timeAgo(agent.last_action_at)}</span>
          )}
        </div>
      )}

      {/* Messages */}
      <div className={styles.messagesSection}>
        <div className={styles.messagesSectionLabel}>AGENT TRANSMISSIONS</div>
        <div className={styles.messages}>
          {messages.map((msg) => (
            <div key={msg.id} className={`${styles.message} ${styles[`msg_${MSG_COLORS[msg.message_type]}`]}`}>
              <span className={styles.msgIcon}>{MSG_ICONS[msg.message_type]}</span>
              <div className={styles.msgBody}>
                <span className={styles.msgType}>{msg.message_type.toUpperCase()}</span>
                <p className={styles.msgContent}>{msg.content}</p>
                <span className={styles.msgTime}>{timeAgo(msg.created_at)}</span>
              </div>
              {msg.is_claude_generated && (
                <span className={styles.claudeBadge} title="Generated by Claude">AI</span>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
