"use client";

import { useState } from "react";
import styles from "./PlanningPanel.module.css";
import type { AgentPlan } from "@/lib/supabase/types";

interface Props {
  plan: AgentPlan;
}

const RISK_CONFIG = {
  low: { label: "LOW RISK", color: "green" },
  medium: { label: "MEDIUM RISK", color: "amber" },
  high: { label: "HIGH RISK", color: "red" },
  critical: { label: "CRITICAL", color: "red" },
};

const PRIORITY_CONFIG = {
  high: { label: "HIGH", color: "red" },
  medium: { label: "MED", color: "amber" },
  low: { label: "LOW", color: "dim" },
};

export default function PlanningPanel({ plan }: Props) {
  const [mode, setMode] = useState<"autonomous" | "manual">("autonomous");
  const [applied, setApplied] = useState(plan.applied);

  const risk = RISK_CONFIG[plan.risk_level];
  const actions = plan.recommended_actions as Array<{
    action: string; priority: string; detail: string;
  }>;
  const steps = plan.next_steps as string[];

  return (
    <div className={styles.panel}>
      <div className={styles.header}>
        <span className={styles.headerTitle}>PLANNING</span>
        <span className={`${styles.riskBadge} ${styles[`risk_${risk.color}`]}`}>
          {risk.label}
        </span>
      </div>

      {/* Risk summary */}
      <div className={styles.riskSummary}>
        <span className={styles.riskSummaryLabel}>RISK ASSESSMENT</span>
        <p className={styles.riskSummaryText}>{plan.risk_summary}</p>
      </div>

      {/* Recommended actions */}
      <div className={styles.section}>
        <div className={styles.sectionLabel}>RECOMMENDED ACTIONS</div>
        <div className={styles.actions}>
          {actions.map((a, i) => {
            const pConf = PRIORITY_CONFIG[a.priority as keyof typeof PRIORITY_CONFIG] || PRIORITY_CONFIG.low;
            return (
              <div key={i} className={styles.action}>
                <span className={`${styles.actionPriority} ${styles[`priority_${pConf.color}`]}`}>
                  {pConf.label}
                </span>
                <div className={styles.actionContent}>
                  <span className={styles.actionName}>{a.action}</span>
                  <span className={styles.actionDetail}>{a.detail}</span>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Next steps */}
      <div className={styles.section}>
        <div className={styles.sectionLabel}>NEXT STEPS</div>
        <div className={styles.steps}>
          {steps.map((step, i) => (
            <div key={i} className={styles.step}>
              <span className={styles.stepNum}>{String(i + 1).padStart(2, "0")}</span>
              <span className={styles.stepText}>{step}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Controls */}
      <div className={styles.controls}>
        <div className={styles.modeRow}>
          <span className={styles.modeLabel}>OPERATOR MODE</span>
          <div className={styles.modeToggle}>
            <button
              className={`${styles.modeBtn} ${mode === "autonomous" ? styles.modeBtnActive : ""}`}
              onClick={() => setMode("autonomous")}
            >
              AUTO
            </button>
            <button
              className={`${styles.modeBtn} ${mode === "manual" ? styles.modeBtnActiveManual : ""}`}
              onClick={() => setMode("manual")}
            >
              MANUAL
            </button>
          </div>
        </div>

        <div className={styles.btnGroup}>
          <button
            className={`${styles.btn} ${styles.btnApply} ${applied ? styles.btnApplied : ""}`}
            onClick={() => setApplied(true)}
            disabled={applied}
          >
            {applied ? "✓ PLAN APPLIED" : "APPLY PLAN"}
          </button>
          <button className={`${styles.btn} ${styles.btnPause}`}>
            PAUSE AUTOMATION
          </button>
        </div>
      </div>

      {plan.is_claude_generated && (
        <div className={styles.claudeFooter}>
          <span className={styles.claudeFooterText}>
            ⬡ PLAN GENERATED BY FOREMAN-7 (CLAUDE)
          </span>
        </div>
      )}
    </div>
  );
}
